[package]
name = "simpleserve"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.56"
regex = "1.9.3"
urlencoding = "2.1.3"
